# Generated by Django 4.1.7 on 2023-02-22 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedrooms', models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared')], default='Private', max_length=7)),
                ('bathrooms', models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared')], default='Private', max_length=7)),
                ('move_in_date', models.DateField(default=django.utils.timezone.now)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('has_dryer', models.BooleanField(default=False)),
                ('has_dishwasher', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_bbq_facilities', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='static/avatars/')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
