# Generated by Django 4.1.7 on 2023-03-06 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='room',
            new_name='apartment',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'apartment')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
