# Generated by Django 4.1.7 on 2023-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
