# Generated by Django 4.1.7 on 2023-03-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('provider', 'Provider'), ('seeker', 'Seeker')], max_length=10, null=True),
        ),
    ]
