# Generated by Django 4.1.7 on 2023-03-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_message_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
