# Generated by Django 4.1.7 on 2023-03-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('provider', 'Roommate Provider'), ('seeker', 'Roommate Seeker')], max_length=10, null=True),
        ),
    ]
