# Generated by Django 4.1.7 on 2023-03-08 16:28

from django.db import migrations, models
import roommate.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0003_image_remove_apartment_image_apartment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=roommate.models.get_upload_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
