# Generated by Django 4.1.7 on 2023-03-16 17:29

from django.db import migrations, models
import roommate.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=roommate.models.get_upload_path),
        ),
    ]
