# Generated by Django 4.1.7 on 2023-03-08 17:12

from django.db import migrations, models
import roommate.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0004_remove_apartment_images_apartment_image_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=roommate.models.get_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='apartment',
            name='images',
            field=models.ManyToManyField(blank=True, to='roommate.apartmentimage'),
        ),
    ]
