# Generated by Django 4.1.7 on 2023-03-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0004_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roommate.apartment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='roommate.apartmentimage'),
        ),
    ]
